### ISSUE TITLE
Possible memory leak when using TypeApi.<:<

### ISSUE THREAD

**Issue by zella** [scaldi/scaldi-jsr330#51]
According https://github.com/scala/bug/issues/8302 `TypeApi.<:<` invocations should be wrapped into `JavaUniverse.undoLog.undo()`

This api used in `injectSymbol` method.

**Comment by dave-handy** [comment]
Thanks! This looks fairly straightforward. There are plenty of uses of `<:<` in the scaldi core module as well, so I'll have to take a fairly broad look at this.
